<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE widget [
        <!ELEMENT widget (name|description|author|content|access|preference|feature|plugin)*>
        <!ATTLIST widget
                id CDATA #REQUIRED
                version CDATA #REQUIRED
                xmlns CDATA #REQUIRED
                xmlns:cdv CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ATTLIST author
                email CDATA #REQUIRED
                href CDATA #REQUIRED>
        <!ELEMENT content (#PCDATA)>
        <!ATTLIST content
                src CDATA #REQUIRED>
        <!ELEMENT access (#PCDATA)>
        <!ATTLIST access
                origin CDATA #REQUIRED>
        <!ELEMENT preference (#PCDATA)>
        <!ATTLIST preference
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT feature (param)*>
        <!ATTLIST feature
                name CDATA #REQUIRED>
        <!ELEMENT param (#PCDATA)>
        <!ATTLIST param
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                onload CDATA #REQUIRED>
        <!ELEMENT plugin (variable)*>
        <!ATTLIST plugin
                name CDATA #REQUIRED
                spec CDATA #IMPLIED>
        <!ELEMENT variable (#PCDATA)>
        <!ATTLIST variable
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        ]>
<widget id="com.ionicframework.clothingapp633622" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
  <name>foodDemoApp</name>
  <description>
        An Ionic Framework and Cordova project.
    </description>
  <author email="you@example.com" href="http://example.com.com/">
      Your Name Here
    </author>
  <content src="index.html"/>
  <access origin="*"/>
  <preference name="webviewbounce" value="false"/>
  <preference name="UIWebViewBounce" value="false"/>
  <preference name="DisallowOverscroll" value="true"/>
  <preference name="android-minSdkVersion" value="16"/>
  <preference name="BackupWebStorage" value="none"/>
  <feature name="StatusBar">
    <param name="ios-package" value="CDVStatusBar" onload="true"/>
  </feature>
  <plugin name="phonegap-plugin-push" spec="~1.8.2">
    <variable name="SENDER_ID" value="528602483901" />
  </plugin>
  <plugin name="com.paypal.cordova.mobilesdk"/>
</widget>